spring.application.name=spring-security-2

# "mysql" below = Docker container name (defined in docker-compose.yml)
spring.datasource.url=jdbc:mysql://mysql:3306/springsecuritynew?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true